export const DEFAULT_CSV_DATA = `,,fáze 0,fáze 1,fáze 2,fáze 3,fáze 4,fáze 5,fáze 6,fáze 7,fáze 8,fáze 9,fáze 10,fáze 11,fáze 12,fáze 13
ONKO,ozařovny (H2 - 1.NP),H2p - 1.PP+1.NP: výstavba magnetické rezonance (H2 přístavba dále jen H2p). H2 - 1.NP : vystěhování kartotéky a vyšetřoven. Dočasně přestěhovány do prázdných prostor v H1 - 1.NP po vystěhování do P4,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení. Rozšíření provozu o ambulance v H1 - 1.NP,provoz bez omezení,provoz bez omezení,provoz bez omezení,"Omezení stavbou H2p - 2.NP - stavba lůžková jednotka komplexní podpůrné péče - onkologie. Omezení výstavbou H2p - 3.NP - stavba Oddělení 24A-JIP - Jednotka intenzivní respirační péče - 8 lůžek. Omezení výstavbou H2p - 4.NP technologie na střeše JIP. Omezení hlukem a vibracemi. H1,H2 krček - úprava krčku mezi budovami provozní omezení.",Omezení stavebními úpravami vstupu do budovy H1 a H2 od ředitelství,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení
ONKO,ambulance (H1 - 1.NP),H1 - 1.NP: vystěhování do P4 a uvolnění prostor pro stavbu,volný prostor pro stavby,H1 - 1.NP 2/3 podlaží volný prostor pro stavby. 1/3 realizace centrálních šaten pro Plicní,H1 - 1.NP 2/3 podlaží realizace ambulancí oddělení ozařoven onkologie. 1/3 provoz centrálních šaten pro Plicní,H1 - 1.NP 2/3 podlaží provoz ambulancí oddělení ozařoven onkologie. 1/3 provoz centrálních šaten pro Plicní,H1 - 1.NP 2/3 podlaží provoz ambulancí oddělení ozařoven onkologie. 1/3 provoz centrálních šaten pro Plicní,H1 - 1.NP 2/3 podlaží provoz ambulancí oddělení ozařoven onkologie. 1/3 provoz centrálních šaten pro Plicní,H1 - 1.NP 2/3 podlaží provoz ambulancí oddělení ozařoven onkologie. 1/3 provoz centrálních šaten pro Plicní,"H1 - 1.NP 2/3 podlaží provoz ambulancí oddělení ozařoven onkologie (H1,H2 krček - úprava krčku mezi budovami provozní omezení.). 1/3 provoz centrálních šaten pro Plicní. ",Omezení stavebními úpravami vstupu do budovy H1 a H2 od ředitelství,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení
ONKO,oddělení brachyterapie (H2-2.NP),provoz bez omezení,provoz bez omezení,"provoz s omezeními. Realizace centrálních šaten pro onkologii, omezení hlukem, vibracemi. ",provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení,provoz bez omezení
ONKO,stacionář (H2 - 2.NP),H2 - 2.NP: vystěhování stacionáře do P4 a uvolnění prostor pro stavbu,,,,,,,,,,,,,
,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,
,,,H1p - 1.PP až 6.NP stavba přístavby na celou výšku H1. Omezení jednotlivých oddělení hlukem(H1 přístavba dále jen H1p),,,,,,,,,,,,`;
